name: my_workflows

on: push

jobs: 
    first_job:
        runs-on: ubuntu-24.04
        steps: 
        - name: Checkout-repo
          uses: actions/checkout@v4

        - name: list
          run: |
            echo "My first git hub action job"
            ls -ltra
            cat READMR.md
